name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    # - name: Run tests
    #   run: |
    #     pip install pytest
    #     pytest tests

    - name: (Optional) Build Docker image
      if: github.ref == 'refs/heads/main'
      run: docker build -t aqi-forecaster .

    - name: (Optional) Push Docker image to Docker Hub
      if: github.ref == 'refs/heads/main'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        docker tag aqi-forecaster $DOCKER_USERNAME/aqi-forecaster:latest
        docker push $DOCKER_USERNAME/aqi-forecaster:latest